name: flutter_aria2c_wrapper
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  json_rpc_2: ^3.0.2
  process_run: ^1.2.0
  web_socket_channel: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
